package com.civet.common.menu.dao;

import com.civet.common.menu.entity.TMenu;

public interface TMenuMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 *
	 * @mbggenerated Thu Feb 23 10:20:39 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 *
	 * @mbggenerated Thu Feb 23 10:20:39 CST 2017
	 */
	int insert(TMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 *
	 * @mbggenerated Thu Feb 23 10:20:39 CST 2017
	 */
	int insertSelective(TMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 *
	 * @mbggenerated Thu Feb 23 10:20:39 CST 2017
	 */
	TMenu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 *
	 * @mbggenerated Thu Feb 23 10:20:39 CST 2017
	 */
	int updateByPrimaryKeySelective(TMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_menu
	 *
	 * @mbggenerated Thu Feb 23 10:20:39 CST 2017
	 */
	int updateByPrimaryKey(TMenu record);

}