package com.civet.common.menu.entity;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.description
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.groupid
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.isDefault
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    private Integer isdefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.description
     *
     * @return the value of t_menu.description
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.description
     *
     * @param description the value for t_menu.description
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.groupid
     *
     * @return the value of t_menu.groupid
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.groupid
     *
     * @param groupid the value for t_menu.groupid
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.isDefault
     *
     * @return the value of t_menu.isDefault
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.isDefault
     *
     * @param isdefault the value for t_menu.isDefault
     *
     * @mbggenerated Thu Feb 23 10:20:39 CST 2017
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }
}