package com.civet.note.dao;

import com.civet.note.entity.TMenu;

public interface TMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Tue Feb 28 22:17:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Tue Feb 28 22:17:04 CST 2017
     */
    int insert(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Tue Feb 28 22:17:04 CST 2017
     */
    int insertSelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Tue Feb 28 22:17:04 CST 2017
     */
    TMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Tue Feb 28 22:17:04 CST 2017
     */
    int updateByPrimaryKeySelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Tue Feb 28 22:17:04 CST 2017
     */
    int updateByPrimaryKey(TMenu record);
}