package com.civet.note.dao;

import com.civet.note.entity.TUser;

public interface TUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Fri Mar 24 15:50:24 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Fri Mar 24 15:50:24 CST 2017
	 */
	int insert(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Fri Mar 24 15:50:24 CST 2017
	 */
	int insertSelective(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Fri Mar 24 15:50:24 CST 2017
	 */
	TUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Fri Mar 24 15:50:24 CST 2017
	 */
	int updateByPrimaryKeySelective(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Fri Mar 24 15:50:24 CST 2017
	 */
	int updateByPrimaryKey(TUser record);
}