package com.civet.note.dao;

import com.civet.note.entity.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	int insertSelective(User record);
}