package com.civet.note.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mail
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qq
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.tel
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	private String tel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mail
	 * @return  the value of user.mail
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mail
	 * @param mail  the value for user.mail
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qq
	 * @return  the value of user.qq
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qq
	 * @param qq  the value for user.qq
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.tel
	 * @return  the value of user.tel
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.tel
	 * @param tel  the value for user.tel
	 * @mbggenerated  Tue Feb 28 22:17:04 CST 2017
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}
}